Repository verdaccio/ui, pull requests merged in 2019-10, with the labels that each got.

#129 Version Component - Replaced classes by func. comp
  src/components/Versions/Versions.test.tsx
  src/components/Versions/Versions.tsx
  src/components/Versions/VersionsHistoryList.tsx
  src/components/Versions/VersionsTagList.tsx
  src/components/Versions/__snapshots__/Versions.test.tsx.snap
  src/components/Versions/styles.ts
  types/packageMeta.ts
Labels: PR: needs review, good first issue, hacktoberfest 🎃

#144 fix: tarball download not working on Firefox and Edge
  src/utils/url.ts
Labels: hacktoberfest 🎃

#130 DetailContainer Component - Replaced class by func. comp
  src/components/ActionBar/ActionBar.tsx
  src/components/AutoComplete/styles.tsx
  src/components/AvatarTooltip/AvatarTooltip.tsx
  src/components/CopyToClipBoard/CopyToClipBoard.tsx
  src/components/CopyToClipBoard/styles.ts
  src/components/Dependencies/Dependencies.tsx
  src/components/DetailContainer/DetailContainer.test.tsx
  src/components/DetailContainer/DetailContainer.tsx
  src/components/DetailContainer/DetailContainerContent.tsx
  src/components/DetailContainer/DetailContainerContentReadme.tsx
  src/components/DetailContainer/DetailContainerTabs.tsx
  src/components/DetailContainer/__snapshots__/DetailContainer.test.tsx.snap
  src/components/DetailContainer/styles.ts
  src/components/DetailContainer/tabs.ts
  src/components/DetailContainer/types.ts
  src/components/Developers/__snapshots__/Developers.test.tsx.snap
  src/components/Header/Header.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/Header/styles.ts
  src/components/Package/Package.tsx
  src/components/Package/styles.ts
  src/components/TextField/TextField.tsx
  src/muiComponents/IconButton/IconButton.tsx
  src/muiComponents/IconButton/index.ts
  src/muiComponents/TextField/TextField.test.tsx
  src/muiComponents/TextField/TextField.tsx
  src/muiComponents/TextField/__snapshots__/TextField.test.tsx.snap
  src/muiComponents/TextField/index.ts
  src/muiComponents/Tooltip/Tooltip.tsx
  src/muiComponents/Tooltip/index.ts
Labels: PR: needs review, good first issue, hacktoberfest 🎃

#155 Fix some warnings in console
  src/components/DetailSidebar/DetailSidebar.tsx
  src/components/DetailSidebar/styles.ts
  src/components/Footer/styles.ts
Labels: hacktoberfest 🎃

#156 refactor: convert Dist component to hooks
  src/components/Dist/Dist.test.tsx
  src/components/Dist/Dist.tsx
Labels: hacktoberfest 🎃

#158 Use React.lazy for loading components
  src/router.tsx
  src/utils/asyncComponent.tsx
Labels: hacktoberfest 🎃

#150 refactor: convert Author component to hooks
  src/components/Author/Author.test.tsx
  src/components/Author/Author.tsx
  src/components/Package/Package.tsx
  types/packageMeta.ts
Labels: PR: needs review, good first issue, hacktoberfest 🎃

#152 Install Component - Replaced class by func. comp
  src/components/Install/Install.test.tsx
  src/components/Install/Install.tsx
  src/components/Install/InstallListItem.tsx
  src/components/Install/__partials__/data.json
  src/components/Install/__snapshots__/Install.test.tsx.snap
  src/components/Install/styles.ts
  types/packageMeta.ts
Labels: PR: needs review, good first issue, hacktoberfest 🎃

#153 Fix a few ts-ignore
  src/App/App.tsx
  src/components/ActionBar/ActionBar.test.tsx
  src/components/ActionBar/ActionBar.tsx
  src/components/Dependencies/Dependencies.tsx
  src/components/Developers/Developers.tsx
  src/components/Engines/Engines.test.tsx
  src/components/Footer/Footer.test.tsx
  src/components/Footer/Footer.tsx
  src/components/Footer/styles.ts
  src/components/Header/Header.tsx
  src/components/Header/styles.ts
  src/components/Icon/Icon.tsx
  src/components/Label/Label.tsx
  src/components/Layout/Layout.tsx
  src/components/Package/Package.tsx
  src/components/Package/styles.ts
  src/components/Repository/Repository.test.tsx
  src/components/Spinner/Spinner.tsx
  src/components/Spinner/styles.ts
  src/utils/api.ts
  src/utils/styles/colors.ts
  src/utils/styles/media.ts
  types/index.ts
Labels: hacktoberfest 🎃

#142 Header Component - Replaced class by func. comp
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderGreetings.tsx
  src/components/Header/HeaderInfoDialog.tsx
  src/components/Header/HeaderLeft.tsx
  src/components/Header/HeaderLogo.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/Header/HeaderRight.tsx
  src/components/Header/HeaderToolTip.tsx
  src/components/Header/HeaderToolTipIcon.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/RegistryInfoDialog/RegistryInfoDialog.tsx
Labels: good first issue, hacktoberfest 🎃

#192 E2E integration with puppeteer
  .circleci/config.yml
  jest/jest.config.js
  package.json
  test/e2e/.eslintrc
  test/e2e/config/config-protected-e2e.yaml
  test/e2e/config/config-scoped-e2e.yaml
  test/e2e/e2e.spec.js
  test/e2e/partials/pkg-protected.js
  test/e2e/partials/pkg-scoped.js
  test/e2e/plugins/theme.js
  test/e2e/pre-setup.js
  test/e2e/puppeteer_environment.js
  test/e2e/registry-launcher.ts
  test/e2e/request.ts
  test/e2e/server.ts
  test/e2e/setup.js
  test/e2e/teardown.js
  test/jest.config.e2e.js
  yarn.lock
Labels: hacktoberfest 🎃

#190 Added typings for getRecentReleases
  src/components/Package/Package.tsx
  src/utils/calls.ts
  src/utils/package.ts
  tsconfig.json
Labels: hacktoberfest 🎃

#201 chore(deps): remove types from dependencies
  package.json
Labels: bug, dependencies, high-priority

#171 Version Page - Replaces class by func.
  src/pages/Version/Version.test.tsx
  src/pages/Version/Version.tsx
  src/pages/Version/VersionContextProvider.tsx
  src/pages/Version/VersionLayout.tsx
  src/pages/Version/__partials__/data.json
  src/pages/Version/context.ts
  src/pages/Version/get-route-package-name.ts
  src/pages/Version/index.ts
  src/pages/Version/is-package-version-valid.ts
  src/pages/Version/styles.ts
  src/pages/Version/types.ts
  src/router.tsx
Labels: PR: needs review

#207 chore(tests): remove snapshot test and add more descriptive ones (Spinner.tsx)
  src/components/Spinner/Spinner.test.tsx
  src/components/Spinner/__snapshots__/Spinner.test.tsx.snap
Labels: hacktoberfest 🎃

#206 chore(tests): remove snapshot test and fix its description (UpLinks.tsx)
  src/components/UpLinks/UpLinks.test.tsx
  src/components/UpLinks/__snapshots__/UpLinks.test.tsx.snap
Labels: hacktoberfest 🎃

#159 Routes - Replaced class by func. comp
  src/App/App.test.tsx
  src/App/App.tsx
  src/App/AppContext.tsx
  src/App/AppRoute.tsx
  src/router.tsx
  src/utils/package.ts
Labels: PR: needs review

#210 Improved Typings for API class
  src/components/Search/Search.tsx
  src/utils/api.test.ts
  src/utils/api.ts
  src/utils/calls.ts
Labels: hacktoberfest 🎃

#211 fix(installItemList): changed the wrong icon
  src/components/Install/InstallListItem.tsx
Labels: hacktoberfest 🎃

#214 refactor: adds test for registry info component
  src/components/RegistryInfoContent/RegistryInfoContent.test.tsx
  src/components/RegistryInfoContent/__snapshots__/RegistryInfoContent.test.tsx.snap
Labels: hacktoberfest 🎃

#213 refactor: adds no uplink spec
  src/components/UpLinks/UpLinks.test.tsx
  src/components/UpLinks/__snapshots__/UpLinks.test.tsx.snap
Labels: hacktoberfest 🎃

#216 Card Component - Introduced ForwardRef
  src/components/Dependencies/styles.ts
  src/components/DetailSidebar/DetailSidebar.tsx
  src/components/Help/styles.ts
  src/components/NotFound/styles.ts
  src/muiComponents/Card/Card.tsx
  src/muiComponents/Card/index.ts
Labels: PR: needs review

#219 refactor:116[PackageList] component is converted to functional
  src/components/PackageList/PackageList.tsx
  src/components/PackageList/Packagelist.test.tsx
  src/components/PackageList/index.ts
  src/pages/home/Home.tsx
Labels: hacktoberfest 🎃

#218 Divider Component - Introduced ForwardRef
  src/components/PackageList/PackageList.tsx
  src/muiComponents/Divider/Divider.tsx
  src/muiComponents/Divider/index.ts
Labels: PR: needs review

#227 Migrate eslint@6.6.0
  package.json
  src/App/App.tsx
  src/components/ActionBar/ActionBar.tsx
  src/components/AutoComplete/AutoComplete.tsx
  src/components/AvatarTooltip/AvatarTooltip.tsx
  src/components/DetailContainer/DetailContainerTabs.tsx
  src/components/DetailSidebar/DetailSidebar.tsx
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/Header/HeaderRight.tsx
  src/components/Header/HeaderToolTipIcon.tsx
  src/components/Install/InstallListItem.tsx
  src/components/Login/Login.tsx
  src/components/NotFound/NotFound.tsx
  src/components/Package/Package.test.tsx
  src/components/Package/Package.tsx
  src/components/Readme/Readme.tsx
  src/components/RegistryInfoContent/RegistryInfoContent.tsx
  src/components/Search/Search.tsx
  src/components/Versions/Versions.test.tsx
  src/muiComponents/ListItem/ListItem.tsx
  src/pages/Version/index.ts
  src/utils/api.test.ts
  src/utils/calls.ts
  src/utils/cli-utils.ts
  src/utils/file-size.ts
  src/utils/login.test.ts
  src/utils/package.test.ts
  test/e2e/e2e.spec.js
  yarn.lock
Labels: hacktoberfest 🎃

#228 chore: add canary package generator
  .github/workflows/canary.yml
  .github/workflows/main.yml
  package.json
Labels: PR: needs review
