Repository verdaccio/ui, pull requests merged in 2019-09, with the labels that each got.

#131 Chore: pumped mui version
  package.json
  src/components/Developers/__snapshots__/Developers.test.tsx.snap
  yarn.lock
Labels: dependencies, high-priority

#134 fix: correctly load font files - closes #128
  src/App/App.tsx
  src/styles/typeface-roboto.css
  tools/webpack.config.js
Labels: hold

#136 fix: sidebar view on small screens
  src/pages/Version/Layout.tsx
Labels: bug
