Repository verdaccio/ui, pull requests merged in 2019-11, with the labels that each got.

#239 chore: updated material-ui dependencies
  package.json
  src/components/Author/__snapshots__/Author.test.tsx.snap
  src/components/Developers/__snapshots__/Developers.test.tsx.snap
  src/components/Engines/__snapshots__/Engines.test.tsx.snap
  src/components/Install/__snapshots__/Install.test.tsx.snap
  src/components/Login/__snapshots__/Login.test.tsx.snap
  src/components/Repository/__snapshots__/Repository.test.tsx.snap
  src/components/Search/__snapshots__/Search.test.tsx.snap
  src/muiComponents/TextField/__snapshots__/TextField.test.tsx.snap
  yarn.lock
Labels: PR: needs review, dependencies

#246 Fix e2e
  package.json
  src/components/Help/Help.tsx
  src/components/Package/Package.tsx
  test/e2e/config/config-protected-e2e.yaml
  test/e2e/config/config-scoped-e2e.yaml
  test/e2e/e2e.spec.js
  test/e2e/setup.js
  yarn.lock
Labels: high-priority

#240 Refactor: Created Reset CSS and added local fonts
  src/App/App.tsx
  src/components/Footer/__snapshots__/Footer.test.tsx.snap
  src/components/Icon/__snapshots__/Icon.test.tsx.snap
  src/components/Icon/styles.ts
  src/design-tokens/ResetStyles.tsx
  src/design-tokens/StyleBaseline.tsx
  src/utils/styles/global.ts
  tools/webpack.config.js
  types/custom.d.ts
  types/files.d.ts
Labels: PR: needs review

#209 Converted App component from class to func.
  src/App/App.test.tsx
  src/App/App.tsx
  src/App/AppContext.ts
  src/App/AppContext.tsx
  src/App/AppContextProvider.tsx
  src/App/AppRoute.tsx
  src/App/__snapshots__/App.test.tsx.snap
  src/App/index.ts
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderGreetings.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/Header/HeaderRight.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/Login/Login.tsx
  src/components/Login/__snapshots__/Login.test.tsx.snap
Labels: PR: needs review

#300 fix: correctly reference registry url from options
  jest/jestEnvironment.js
  jest/setup.ts
  src/utils/url.test.ts
  src/utils/url.ts
Labels: PR: needs review
