Repository verdaccio/ui, pull requests merged in 2019-12, with the labels that each got.

#339 Search Component - Replaced class by func. comp
  .eslintrc
  jest/unit/components/__mocks__/.eslintrc
  package.json
  src/App/App.tsx
  src/App/AppContextProvider.tsx
  src/components/AutoComplete/AutoComplete.tsx
  src/components/Header/Header.tsx
  src/components/Search/Search.test.tsx
  src/components/Search/Search.tsx
  src/components/Search/SearchAdornment.tsx
  src/components/Search/__snapshots__/Search.test.tsx.snap
  src/muiComponents/.eslintrc
  src/utils/test-enzyme.ts
  src/utils/test-react-testing-library.tsx
  test/e2e/.eslintrc
  tsconfig.json
  types/jest-dom.d.ts
  yarn.lock
Labels: PR: needs review

#345 Replaced date-fns with dayjs
  jest/unit/components/__mocks__/token.ts
  package.json
  src/components/Package/Package.tsx
  src/components/UpLinks/UpLinks.tsx
  src/components/UpLinks/__snapshots__/UpLinks.test.tsx.snap
  src/components/Versions/VersionsHistoryList.tsx
  src/utils/package.test.ts
  src/utils/package.ts
  yarn.lock
Labels: PR: needs review, PoC, dependencies

#341 Login Dialog Component - Replaced class by func. comp + added react-hook-form
  .eslintrc
  .vscode/settings.json
  jest/setup.ts
  package.json
  src/App/App.tsx
  src/App/AppContext.ts
  src/App/AppContextProvider.tsx
  src/App/AppRoute.tsx
  src/components/ActionBar/ActionBarAction.tsx
  src/components/Dist/Dist.tsx
  src/components/Engines/Engines.tsx
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/Login/Login.test.tsx
  src/components/Login/Login.tsx
  src/components/Login/__snapshots__/Login.test.tsx.snap
  src/components/Login/index.ts
  src/components/Login/styles.ts
  src/components/LoginDialog/LoginDialog.test.tsx
  src/components/LoginDialog/LoginDialog.tsx
  src/components/LoginDialog/LoginDialogCloseButton.tsx
  src/components/LoginDialog/LoginDialogForm.tsx
  src/components/LoginDialog/LoginDialogFormError.tsx
  src/components/LoginDialog/LoginDialogHeader.tsx
  src/components/LoginDialog/__snapshots__/LoginDialog.test.tsx.snap
  src/components/LoginDialog/index.ts
  src/components/Package/Package.tsx
  src/components/Repository/Repository.tsx
  src/pages/Version/Version.test.tsx
  src/utils/login.test.ts
  src/utils/login.ts
  test/e2e/e2e.spec.js
  yarn.lock
Labels: PR: needs review

#375 Feat: added "Fund this package" button
  .vscode/settings.json
  src/components/DetailSidebar/DetailSidebar.tsx
  src/components/DetailSidebar/DetailSidebarFundButton.tsx
  src/components/DetailSidebar/DetailSidebarTitle.tsx
  src/components/DetailSidebar/styles.ts
  src/design-tokens/theme.ts
  tools/dev.server.js
  types/packageMeta.ts
  ~/.config/verdaccio/storage_demo_gif/.verdaccio-db.json
Labels: PR: needs review

#384 Chore: bump @material-ui/core from 4.7.2 to 4.8.0
  package.json
  src/App/__snapshots__/App.test.tsx.snap
  yarn.lock
Labels: dependencies

#396 fix: add missing trailing slash to publicPath - closes #395
  tools/webpack.config.js
Labels: PR: needs review
