Repository verdaccio/ui, pull requests merged in 2019-07, with the labels that each got.

#86 fix: 83 support deprecated license object properties
  src/components/Dist/Dist.test.tsx
  src/components/Dist/Dist.tsx
  src/components/Dist/__snapshots__/Dist.test.tsx.snap
  src/components/Package/Package.tsx
  src/utils/package.test.ts
  src/utils/package.ts
  types/packageMeta.ts
Labels: PR: needs review

#91 feat: updated typescript to 3.5.2
  package.json
  src/App/App.test.tsx
  src/App/App.tsx
  src/utils/calls.ts
  yarn.lock
Labels: enhancement

#85 refactor: 78 replace node sass with emotion
  package.json
  src/App/App.tsx
  src/App/app.scss
  src/App/styles.ts
  src/components/Header/Header.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/Login/Login.tsx
  src/components/Login/__snapshots__/Login.test.tsx.snap
  src/components/Login/login.scss
  src/components/Login/styles.ts
  src/components/PackageList/PackageList.tsx
  src/components/PackageList/packageList.scss
  src/components/PackageList/styles.ts
  src/pages/home/home.scss
  src/styles/core.scss
  src/styles/global.scss
  src/styles/main.scss
  src/styles/mixins.scss
  src/styles/typeface-roboto.css
  src/styles/variables.scss
  src/utils/styles/global.ts
  src/utils/styles/media.ts
  tools/webpack.config.js
  yarn.lock
Labels: PR: needs review, enhancement, hold

#101 fix: 76 download button hidden for localhost
  package.json
  src/history.ts
  src/router.tsx
  src/utils/url.test.ts
  src/utils/url.ts
  yarn.lock
Labels: PR: needs review

#110 fix: download protected tarballs
  package.json
  src/components/ActionBar/ActionBar.test.tsx
  src/components/ActionBar/ActionBar.tsx
  src/components/ActionBar/__snapshots__/ActionBar.test.tsx.snap
  src/utils/api.test.ts
  src/utils/api.ts
  src/utils/url.test.ts
  src/utils/url.ts
  tools/dev.server.js
  tools/webpack.dev.config.babel.js
  yarn.lock
Labels: bug, enhancement, high-priority
