Repository verdaccio/ui, pull requests merged in 2019-08, with the labels that each got.

#96 [WIP]chore: adds unit tests for <Repository /> component
  src/components/Repository/Repository.test.tsx
  src/components/Repository/__snapshots__/Repository.test.tsx.snap
Labels: wip

#44 test: BDD / acceptance tests
  codecept.conf.js
  package.json
  test/acceptance/.gitignore
  test/acceptance/Menu_test.js
  test/acceptance/SearchResult_test.js
  test/acceptance/steps_file.js
Labels: discuss, enhancement

#121 fix: missing headers on search endpoint with token
  src/components/Search/Search.test.tsx
  src/components/Search/Search.tsx
  src/pages/Version/Version.test.tsx
  src/utils/calls.ts
Labels: bug

#123 chore: update material-ui@4.x
  package.json
  partials/storage/vue/package.json
  src/components/ActionBar/ActionBar.test.tsx
  src/components/ActionBar/ActionBar.tsx
  src/components/ActionBar/__snapshots__/ActionBar.test.tsx.snap
  src/components/Author/Author.test.tsx
  src/components/Author/Author.tsx
  src/components/Author/__snapshots__/Author.test.tsx.snap
  src/components/Author/styles.ts
  src/components/CopyToClipBoard/CopyToClipBoard.test.tsx
  src/components/CopyToClipBoard/__snapshots__/CopyToClipBoard.test.tsx.snap
  src/components/CopyToClipBoard/styles.ts
  src/components/Dependencies/Dependencies.tsx
  src/components/DetailSidebar/DetailSidebar.tsx
  src/components/Developers/Developers.tsx
  src/components/Developers/__snapshots__/Developers.test.tsx.snap
  src/components/Dist/Dist.test.tsx
  src/components/Dist/Dist.tsx
  src/components/Dist/__snapshots__/Dist.test.tsx.snap
  src/components/Engines/Engines.test.tsx
  src/components/Engines/Engines.tsx
  src/components/Engines/__snapshots__/Engines.test.tsx.snap
  src/components/Header/Header.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/Help/Help.test.tsx
  src/components/Help/Help.tsx
  src/components/Help/__snapshots__/Help.test.tsx.snap
  src/components/Install/Install.test.tsx
  src/components/Install/Install.tsx
  src/components/Install/__snapshots__/Install.test.tsx.snap
  src/components/Install/styles.ts
  src/components/Label/Label.test.tsx
  src/components/Link/Link.test.tsx
  src/components/Loading/__snapshots__/Loading.test.tsx.snap
  src/components/Login/__snapshots__/Login.test.tsx.snap
  src/components/NoItems/__snapshots__/Noitems.test.tsx.snap
  src/components/NotFound/__snapshots__/Notfound.test.tsx.snap
  src/components/Package/Package.tsx
  src/components/Readme/Readme.spec.tsx
  src/components/Repository/Repository.test.tsx
  src/components/Repository/Repository.tsx
  src/components/Repository/__snapshots__/Repository.test.tsx.snap
  src/components/Repository/styles.ts
  src/components/Search/__snapshots__/Search.test.tsx.snap
  src/components/Spinner/__snapshots__/Spinner.test.tsx.snap
  src/components/TextField/TextField.test.tsx
  src/components/TextField/__snapshots__/TextField.test.tsx.snap
  src/components/UpLinks/UpLinks.tsx
  src/components/Versions/Versions.test.tsx
  src/components/Versions/Versions.tsx
  src/components/Versions/__snapshots__/Versions.test.tsx.snap
  src/pages/Version/Version.test.tsx
  tsconfig.json
  yarn.lock
Labels: New UI, high-priority
