Repository verdaccio/ui, pull requests merged in 2020-05, with the labels that each got.

#457 fix: when scope is provided use proper separator
  src/utils/cli-utils.test.ts
  src/utils/cli-utils.ts
Labels: bug, unit test

#463 Feature: Custom favicon
  src/template/index.html
  tools/webpack.prod.config.babel.js
Labels: do not merge

#480 fix: revert custom favicon (#463)
  src/template/index.html
  tools/webpack.prod.config.babel.js
Labels: bug
