Repository verdaccio/ui, pull requests merged in 2020-10, with the labels that each got.

#566 fix(ui): Fix sidebar - developer empty section
  src/pages/Version/DetailSidebar/Developers/Developers.tsx
  src/pages/Version/DetailSidebar/Developers/get-unique-developer-values.ts
Labels: hacktoberfest-accepted

#579 fix(ui): Change no package title size
  src/pages/home/PackageList/Help/Help.tsx
  src/pages/home/PackageList/Help/__snapshots__/Help.test.tsx.snap
Labels: hacktoberfest-accepted

#572 build: migrate from yarn v1 to yarn berry (v2)
  .babelrc
  .circleci/config.yml
  .eslintignore
  .github/workflows/_disabled/security.yml
  .github/workflows/canary.yml
  .github/workflows/main.yml
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/releases/yarn-berry.cjs
  .yarnrc
  .yarnrc.yml
  README.md
  babel.config.js
  jest/identity.js
  jest/jest.config.js
  package.json
  scripts/gh_publish.sh
  scripts/publish.sh
  src/App/AppRoute.tsx
  tsconfig.json
  yarn.lock
Labels: build enhancement, hacktoberfest 🎃, hacktoberfest-accepted

#568 feat(ui): add prefers-color-scheme media query support
  src/design-tokens/ThemeProvider.tsx
Labels: hacktoberfest-accepted

#557 feat: allow deep links on readme pages
  src/utils/sec-utils.ts
Labels: enhancement, hacktoberfest 🎃, hacktoberfest-accepted

#583 chore(lint): fix lint warning for DevelopersTitle
  src/pages/Version/DetailSidebar/Developers/DevelopersTitle.tsx
Labels: enhancement, hacktoberfest 🎃, hacktoberfest-accepted

#584 chore(lint): remove App.tsx lint warnings
  src/App/App.tsx
Labels: hacktoberfest 🎃, hacktoberfest-accepted, lint-issue
