Repository verdaccio/ui, pull requests merged in 2020-01, with the labels that each got.

#411 fix: remove prevent default and use react context
  src/components/DetailSidebar/DetailSidebar.tsx
  src/components/DetailSidebar/DetailSidebarFundButton.test.tsx
  src/components/DetailSidebar/DetailSidebarFundButton.tsx
Labels: bug

#422 [Docs]: Minor tweak
  README.md
Labels: docs

#421 fix: reload packages on log in
  tools/_verdaccio.config.yaml
Labels: bug

#230 chore: add snyk as an action
  .github/workflows/security.yml
Labels: PoC
